config/routes.rb
Ops::Application.routes.draw do
  scope ":locale" do
    resource :session do
      get 'shibboleth'
    end
    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout

    #match '/preferences' => 'users#edit'
#    resources :users, :only => [] do
#       member do
#         get :courses
#       end
#    end

    #resources :courses  # AbstractCourses
    #resources :course_instances, :only => [:index]
    #resources :skills

    # View study guides of other years
    resources :curriculums, :constraints => { :id => /\w+/ } do
      member do
        get 'graph'
        get 'search_skills'
        #get 'search_courses'
        match 'edit/import_csv', :controller => 'curriculums', :action => :import_csv, :via => [:post, :get]
      end

      resources :competence_nodes, :only => [], :controller => 'curriculums/competence_nodes' do
        collection do
          get 'nodes_by_skill_ids'
        end
      end

      resources :competences, :controller => 'curriculums/competences' do
        member do
          get 'graph'
          get 'courselist'
          get 'edit_prereqs'
        end
        
        resources :skills, :controller => 'curriculums/skills', :only => [:show]
        resources :courses, :controller => 'curriculums/courses', :only => [:show]
      end

      resources :courses, :controller => 'curriculums/courses' do  # ScopedCourses
        member do
          get 'edit_prereqs'
          get 'edit_as_a_prereq'
          get 'comments'
          post 'create_comment'
          get 'graph'
        end
      end

      resources :skills, :controller => 'curriculums/skills', :only => [:index, :create, :update, :destroy] do
        member do
          post 'add_prereq'
          post 'remove_prereq'
          put 'update_position'
        end
      end

      resources :roles, :controller => 'curriculums/roles', :only => [:new, :create, :destroy]
    end

    # My Plan
    resource :studyplan, :controller => 'plans', :only => [:show] do
      member do
        get :summary
      end
     
      resources :competences, :controller => 'plans/competences' do
        member do
          # get 'supporting'
          get 'delete'
        end
        
        resources :courses, :controller => 'plans/courses', :only => [:show, :create, :destroy] # show is obsolete
        resources :skills, :controller => 'plans/skills', :only => [:show]                      # obsolete
      end

      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]

      resource :schedule, :controller => 'plans/schedule', :only => [:show]

      resource :curriculum, :controller => 'plans/curriculums', :only => [:show, :edit, :update]
    end

    # Any plan (specify student ID)
    resources :plans, :constraints => { :id => /\w+/ }, :only => [:show, :update] do
      member do
        get :summary
      end
      
      get 'old_schedule', as: 'old_schedule'
      
      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]
#       resources :courses, :controller => 'plans/courses', :only => [:index, :show, :create]  # :except => [:edit, :update]
#       resource :schedule, :controller => 'plans/schedule', :only => [:show, :edit]
#       resource :record, :controller => 'plans/record', :only => [:show]
    end
    
    match 'search_courses' => "abstract_courses#search"
    resources :surveys, :only => [:show, :create], :constraints => { :id => /\w+/ }
  end

  resources :invitations, :only => [:show, :destroy], :id => /[^\/]+/

  #post 'client_side_error', :controller => 'application', as: 'client_side_error'
  match '/client_side_error' => 'application#client_side_error', as: 'client_side_error'
  match '/client_event', to: 'application#log_client_event', as: 'log_client_event'
  
  match '/:locale' => "frontpage#index", :as => :frontpage
  #root :to => "application#redirect_by_locale"
  root :to => "frontpage#index"

end

app/controllers/curriculums/courses_controller.rb
class Curriculums::CoursesController < ApplicationController

  before_filter :load_curriculum

  respond_to :json
  # html for only index, show, new & create (as of 2013-08-09)

  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id] || params[:id])
  end
  
  # GET /courses
  # GET /courses.xml
  def index
    #@courses = @curriculum.courses

    @courses = ScopedCourse.where(:curriculum_id => @curriculum.id)
                .joins(:course_descriptions)
                .where(["course_descriptions.locale = ?", I18n.locale]).includes(:strict_prereqs)
#                 .joins(<<-SQL
#                     INNER JOIN course_descriptions
#                       ON competence_nodes.abstract_course_id = course_descriptions.abstract_course_id
#                   SQL
#                 )

    respond_to do |format|
      #format.html # index.html.erb
      format.json do
        render :json => @courses.select(<<-SQL
            competence_nodes.id,
            competence_nodes.course_code,
            course_descriptions.name AS translated_name
          SQL
        ).to_json(:methods => :strict_prereq_ids, :root => true)
      end
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  # Returns JSON:
  #   {
  #     "scoped_course": {
  #       "course_code":"T-0.000",
  #       "id":5,
  #       "skills": [
  #         {
  #           "id":1231,
  #           "skill_descriptions":[
  #             {
  #               "id":1760,
  #               "locale": "en"
  #               "description": "in english",
  #             },
  #             {...}
  #           ]
  #         },
  #         { another skill... }
  #       ]
  #     }
  #   }
  def show

    respond_to do |format|
      format.html {
        # show.html.erb
        load_plan
        @user = current_user
        @course = ScopedCourse.find(params[:id])
        @competence = nil
        @competence = Competence.find(params[:competence_id]) if params[:competence_id]

        # Log
        @client_session_id = SecureRandom.hex(3)
        if @competence
          log("view_competence_course #{@competence.id} #{@course.id} (#{@client_session_id})")
        else
          log("view_course #{@course.id} (#{@client_session_id})")
        end
        
        render :action => 'show', :layout => 'leftnav'
      }
      format.json {
        @course = ScopedCourse.includes(:skills => [:skill_descriptions, :skill_prereqs, :prereq_to]).find(params[:id])
        render :json => @course.to_json(
          :only => [:id, :course_code],
          :include => {
              :skills => {
                :only => [:id, :icon],
                :include => {
                  :skill_descriptions => {
                    :only => [:id, :locale, :name]
                  },
                  :skill_prereqs => {:only => [:prereq_id, :requirement]},
                  :prereq_to => {:only => [:id, :requirement, :icon]}
                }
              },
              :course_descriptions => {
                :only => [:id, :locale, :name]
              }
          },
          :root => true)
      }
    end
  end

  def edit_prereqs
    @scoped_course = ScopedCourse.find(params[:id])
    @competence_node = @scoped_course
    authorize! :update, @scoped_course

    @hide_help = cookies[:hide_edit_prereqs_help] == 't' ? true : false

    @competence_node_url = curriculum_course_path(:curriculum_id => @curriculum, :course_id => @course)

    render :action => 'edit_prereqs', :layout => 'views/curriculums/wide'
  end

  def edit_as_a_prereq
    @scoped_course = ScopedCourse.find(params[:id])
    @competence_node = @scoped_course
    authorize! :update, @scoped_course

    @hide_help = cookies[:hide_edit_as_a_prereq_help] == 't' ? true : false

    @competence_node_url = curriculum_course_path(:curriculum_id => @curriculum, :course_id => @course)

    render :action => 'edit_as_a_prereq', :layout => 'views/curriculums/wide'
  end

  def comments
    authorize! :update, @curriculum
    
    @scoped_course = ScopedCourse.find(params[:id])
    @new_comment = Comment.new

    render :action => 'comments', :layout => 'views/curriculums/wide'
  end

  def create_comment
    @scoped_course = ScopedCourse.find(params[:id])
    authorize! :update, @curriculum

    @comment = Comment.new(params[:comment])
    @comment.commentable = @scoped_course
    @comment.user = current_user

    @comment.save

    redirect_to comments_curriculum_course_path(:curriculum_id => @curriculum, :id => @scoped_course)
  end

  def new
    authorize! :update, @curriculum

    @scoped_course = ScopedCourse.new
    @scoped_course.curriculum = @curriculum #Curriculum.find(params[:curriculum_id])
    
    render :action => 'new', :layout => 'fixed'
  end

  def create
    authorize! :update, @curriculum
    @curriculum.save  # Expire cache
    
    @course_code = params[:course_code].strip
    if @course_code.blank?
      flash[:error] = t('curriculums.courses.new.course_code_required')
      redirect_to new_curriculum_course_path(:curriculum_id => @curriculum)
      return
    end
    
    # Check if course exists already
    existing_course = ScopedCourse.where(:course_code => @course_code, :curriculum_id => @curriculum.id).first
    if existing_course
      redirect_to edit_curriculum_course_path(:curriculum_id => @curriculum, :id => existing_course)
      return
    end
    
    # Find or create AbstractCourse
    abstract_course = AbstractCourse.find_by_code(@course_code) || AbstractCourse.create(:code => @course_code)

    @scoped_course = ScopedCourse.new(params[:scoped_course])
    @scoped_course.course_code = @course_code
    @scoped_course.curriculum = @curriculum
    @scoped_course.term = @curriculum.term
    @scoped_course.abstract_course = abstract_course

    respond_to do |format|
      format.html do
        if @scoped_course.save
          redirect_to edit_curriculum_course_path(:curriculum_id => @curriculum, :id => @scoped_course)
        else
          render :action => 'new', :layout => 'fixed'
        end
      end
    end
  end

  def edit
    @scoped_course = ScopedCourse.find(params[:id])
    @abstract_course = @scoped_course.abstract_course
    
    authorize! :update, @scoped_course
    
    @course_descriptions = @abstract_course.course_descriptions.all
    REQUIRED_LOCALES.each do |locale|
      course_description = @course_descriptions.select{|desc| desc.locale == locale }[0] 
      
      unless course_description
        course_description = CourseDescription.new(:locale => locale, :name => '')
        @course_descriptions << course_description
      end
      
      @localized_description = course_description if locale == I18n.locale.to_s
    end

    render :action => 'edit', :layout => 'views/curriculums/wide'
  end

  def update
    @curriculum.save  # Expire cache
    @scoped_course = ScopedCourse.find(params[:id])

    authorize! :update, @scoped_course
    
    # Update AbstractCourse if changed
    new_course_code = params[:scoped_course]['course_code'].strip
    if new_course_code != @scoped_course.abstract_course.code
      # If scoped course exists in this curriculum, show error message
      existing_course = ScopedCourse.where(:course_code => new_course_code, :curriculum_id => @curriculum.id).first
      if existing_course
        flash[:error] = "Another course with code #{new_course_code} already exists"
        redirect_to edit_curriculum_course_path(:curriculum_id => @curriculum, :id => @scoped_course)
        return
      end
      
      abstract_course = AbstractCourse.find_by_code(new_course_code) || AbstractCourse.create(:code => new_course_code)
      @scoped_course.abstract_course = abstract_course
    end
    
    # Update CourseDescriptions
    course_descriptions = @scoped_course.abstract_course.course_descriptions.all
    params['course_descriptions'].each do |locale, values|
      # Find or create course_description by locale
      course_description = course_descriptions.select {|desc| desc.locale == locale}[0] ||
        CourseDescription.new(:abstract_course_id => @scoped_course.abstract_course.id, :locale => locale, :name => values[:name]) unless course_description
      
      course_description.name = values[:name]
      
      if params['localized_description'] && params['localized_description']['locale'] == course_description.locale
        course_description.attributes = params['localized_description']
      end
      
      course_description.save
    end
    
    
    @scoped_course.update_comments(params[:comments])
    if @scoped_course.update_attributes(params[:scoped_course])
      flash[:success] = 'Information updated'
    else
      flash[:error] = 'Failed to update information. Please report this problem to staff.'
    end
    
    redirect_to edit_curriculum_course_path(:curriculum_id => @curriculum, :id => @scoped_course)
  end

  def graph
    @scoped_course = ScopedCourse.find(params[:id])

    render :action => 'graph', :layout => 'views/curriculums/wide'
  end

end

app/controllers/plans/courses_controller.rb
class Plans::CoursesController < PlansController

  #before_filter :login_required
  before_filter :load_plan

  # GET /studyplan/courses
  # GET /studyplan/courses.xml
  def index
    authorize! :read, @study_plan
    
    # Log
    @client_session_id = SecureRandom.hex(3)
    log("view_courses (#{@client_session_id})")
    
    respond_to do |format|
      format.html { render :action => 'index', :layout => 'affix-fixed' }
      format.xml  { render :xml => nil }
    end
  end

  # GET /studyplan/courses/1
  # GET /studyplan/courses/1.xml
  def show
    # Obsolete?
    authorize! :read, @study_plan
    @course = ScopedCourse.find(params[:id])
    @competence = nil
    @competence = Competence.find(params[:competence_id]) if params[:competence_id]

    # Log
    @client_session_id = SecureRandom.hex(3)
    if @competence
      log("view_competence_course #{@competence.id} #{@course.id} (#{@client_session_id})")
    else
      log("view_course #{@course.id} (#{@client_session_id})")
    end
    
    render :action => 'show', :layout => 'leftnav'
  end

  # Add course to study plan
  # POST /plans/:id/courses
  def create
    authorize! :update, @study_plan
    
    abstract_course = AbstractCourse.find(params[:abstract_course_id])
    competence_id = Integer(params[:competence_id]) rescue nil
    scoped_course_id = Integer(params[:scoped_course_id]) rescue nil
    
    scoped_course = nil
    
    
    plan_course = @study_plan.add_course(abstract_course, {
      competence_node_id: competence_id,
      scoped_course_id: scoped_course_id,
      manually_added: true
    })
    
    log "add_course #{abstract_course.id}, competence #{competence_id}, scoped_course #{scoped_course_id}"
    
    respond_to do |format|
      format.html {
        if competence_id
          competence = Competence.find(competence_id)
          redirect_to curriculum_competence_path(:curriculum_id => competence.curriculum_id, :id => competence_id), :flash => { :success => t('plans.courses.course_added_to_plan') }
          #studyplan_competence_path(:id => competence_id)
        else
          scoped_course = ScopedCourse.find(scoped_course_id) if scoped_course_id
          redirect_to root_path # FIXME
          # studyplan_competences_path, :flash => { :success => t('plans.courses.course_added_to_plan') }
        end
      }
      # TODO: add error message
      format.json { render json: { status: 'ok', plan_course_id: plan_course.id }.to_json( root: false ) }
    end
    
  end

  # Remove course from study plan. Use abstract_course_id
  # DESTROY /plans/:plan_id/courses/:id
  def destroy
    authorize! :update, @study_plan
    @competence = nil
    @competence = Competence.find(params[:competence_id]) if params[:competence_id]
    
    #if params[:abstract_course_id]
      status = @study_plan.remove_abstract_courses(params[:id])
      log "remove_course #{params[:id]}"
    #else
    #  status = @study_plan.remove_scoped_course(params[:id])
    #  log "remove_scoped_course #{params[:id]}"
    #end
    
    respond_to do |format|
      format.html {
        if @competence
          redirect_to curriculum_competence_path(curriculum_id: @competence.curriculum_id, id: @competence.id), :flash => { :success => t('plans.courses.course_removed_from_plan') }
        else
          redirect_to root_path # FIXME
          #studyplan_competences_path, :flash => { :success => t('plans.courses.course_removed_from_plan') }
        end
      }
      format.json { render json: { status: 'ok' }.to_json( root: false ) }
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

  def skill_prereq(skill_id, prereq_id)
    p = SkillPrereq.find(:first, :conditions => {:skill_id => skill_id, :prereq_id => prereq_id})
    
    return '' unless p
    
    case p.requirement
    when STRICT_PREREQ
      return '<span style="font-size: 125%;">&diams;</span>'.html_safe
    when SUPPORTING_PREREQ
      return '<span style="font-size: 125%; color: gray;">&bull;</span>'.html_safe
    else
      return ''
    end
  end


  def scoped_course_comment(field)
    "<textarea name='comments[#{field}]' class='input-xxlarge' rows='5'>#{html_escape(@scoped_course.comment(field))}</textarea>".html_safe
  end
  
end

app/views/curriculums/courses/skill_editor/_as_a_prereq_editor.html.erb
<div class="row-fluid full-height">

  <%= render 'curriculums/courses/skill_editor/current_course_column' %>

  <% content_for :searchable_column_heading do %>
    <%= t('curriculums.courses.skill_editor.searchable_column.as_a_prereq_column_heading') %>
  <% end %>

  <%= render 'curriculums/courses/skill_editor/searchable_column' %>

</div>

<!--p><%= link_to t(:Back), edit_curriculum_path(@curriculum) %></p-->

<%= render 'curriculums/courses/skill_editor/modals' %>

app/views/curriculums/courses/skill_editor/_competence_node.html.erb
<%# Make sure local variable has default value so that the partial can be rendered
    without explicitly providing the variable. %>
<% skills_sortable = false if not local_assigns.has_key? :skills_sortable %>

<div class="course"
  data-bind="popover: {
              trigger: skillErrorOccurred,
              options: {
                trigger: 'manual',
                html: true,
                template: O4.skillEditor.errorPopoverTemplate,
                title: '<%= t "curriculums.courses.skill_editor.prereq_change_failed_heading" %>',
                content: '<%= t "curriculums.courses.skill_editor.prereq_change_failed_message" %>'
              }
            }">
    <p><span data-bind="text: code"></span> <span data-bind="text: localizedName"></span> <span class="pull-right" data-bind="text: localizedType"></span></p>
    <div data-bind="<% if !skills_sortable.nil? && skills_sortable %>
        sortable: {
          data: skills,
          afterMove: O4.skillEditor.Skill.afterSkillMoved,
          options: {
            cursor: 'move',
            containment: 'parent',
            distance: 10,
            helper: O4.skillEditor.Skill.createDragHelperElement
          }
        }
      <% else %>
        foreach: skills
      <% end %>">
      <div class="skill <%= 'draggable-skill' if skills_sortable %>" data-bind="click: clickSelectTarget,
        css: {
          selected: selected(),
          supporting: prereqType() === 0,
          strict: prereqType() === 1,
          loading: isLoading() || isBeingDeleted()
        }">
        <div class="buttons pull-right" data-bind="visible: $parent.prereqButtonsShown">
          <span data-bind="click: clickToggleSupportingPrereq, clickBubble: false" class="supportingPrereqButton"><%= t('curriculums.courses.skill_editor.supportingPrereqButton') %></span>
          <span data-bind="click: clickToggleStrictPrereq, clickBubble: false" class="strictPrereqButton"><%= t('curriculums.courses.skill_editor.strictPrereqButton') %></span>
        </div>
        <div class="buttons pull-right" data-bind="visible: $parent.editButtonsShown">
          <i class="icon-resize-vertical" title="<%=t '.move_skill' %>"
             data-bind="tooltip: {
               trigger: 'click hover focus',
               placement: 'top'
             }"></i>
          <i class="icon-pencil" data-bind="click: clickEdit" title="<%=t '.edit_skill' %>"></i>
          <i class="icon-trash" data-bind="click: clickDelete, clickBubble: false" title="<%=t '.remove_skill' %>"></i>
        </div>
        <!-- ko foreach: dynamicIcons -->
          <span class="skill-icon" data-bind="css: 'skill-icon-' + $data"></span>
        <!-- /ko -->

        <span class="skill-description"
              data-bind="text: isLoading() ? '<%= t :saving %>' : localizedDescription"></span>
      </div>
    </div>


    <p data-bind="visible: editButtonsShown, with: $root">
      <button class="btn btn-mini" data-bind="click: $root.clickAddSkill"><i class="icon-plus"></i> <%= t 'curriculums.courses.skill_editor.add_skill' %></button>
    </p>
</div>

app/views/curriculums/courses/skill_editor/_current_course_column.html.erb
  <!-- Outcomes -->
  <div class="span6 full-height scroll-vertical">
    <h2><%=t '.outcomes_heading' %></h2>

    <!-- Target node loading error alert box -->
    <div class="row-fluid hide" data-bind="css: { hide: targetNodeLoadFailed() === false }">
      <div class="alert alert-error span11">
        <strong><%= t 'curriculums.courses.skill_editor.load_failed_heading' %></strong> <%= t '.node_load_failure_message' %>
      </div>
    </div>

    <!-- Error alert box for deletion/edit-errors -->
    <div class="row-fluid hide"
      data-bind="css: { hide: skillErrorViewModel.shown() === false },
        with: skillErrorViewModel">
      <div class="alert alert-error span11">
        <button type="button" class="close" data-bind="click: clickClose">&times;</button>
        <strong data-bind="text: heading"></strong> <span data-bind="text: message"></span>
      </div>
    </div>

    <!-- loading icon -->
    <div class="skill-editor-loading-icon" data-bind="css: { hide: targetNodeIsLoading() === false }">
      <%= image_tag 'progress.gif' %>
    </div>

    <div id="target-node" class="hidden"
      data-node-id="<%= @competence_node.id %>"
      data-url="<%= @competence_node_url %>"></div>

    <!-- ko with: node -->
    <%= render :partial => 'curriculums/courses/skill_editor/competence_node',
               :locals => { :skills_sortable => true } %>
    <!-- /ko -->

  </div>

app/views/curriculums/courses/skill_editor/_modals.html.erb
<!-- Skill editor modal -->
<div id="modal-edit-skill" class="modal hide" 
  data-current-locale="<%= I18n.locale %>" 
  data-locales="<%= REQUIRED_LOCALES.join(',') %>" 
  data-curriculum-url="<%= curriculum_path(@curriculum) %>">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3><%= @competence_node.localized_name %> - <%= t('curriculums.courses.skill_editor.add_skill') %></h3>
    </div>
    <div class="modal-body">
      <div class="form-horizontal">
        <!-- ko with: currentlyEditedSkill -->
          <!-- ko foreach: descriptions -->
            <div class="control-group">
              <label class="control-label">
                <span data-bind="text: localizedLocale"></span>
              </label>
              <div class="controls">
                <input type="text" class="input-xxlarge" data-bind="value: name" />
              </div>
            </div>
          <!-- /ko -->
        <!-- /ko -->

        <div class="control-group">
          <div class="controls">
            <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:Cancel) %></button>
            <button class="btn btn-primary" data-bind="click: clickSaveSkill"><%= t(:Save) %></button>
          </div>
        </div>
      </div>
      
      <%= render :partial => 'curriculums/courses/bloom_instructions' %>
    </div>
    <!--
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:Cancel) %></button>
      <button class="btn btn-primary" data-bind="click: clickSaveSkill"><%= t(:Save) %></button>
    </div>
    -->
</div>

<!-- Deletion confirmation modal -->
<div id="modal-confirm-skill-deletion" class="modal hide" 
  data-bind="showModal: showDeletionConfirmationModal, with: currentlyEditedSkill">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 data-bind="text: generateDeletionConfirmationString()"></h4>
  </div>
  <div class="modal-body">
    <p>
      <!-- ko if: prereqTo.length <= 0 -->
        <span class="badge badge-success"><i class="icon-ok icon-white"></i></span>
        <span data-bind="text: $root.i18n['delete_skill_no_dependencies']"></span>
      <!-- /ko -->
      <!-- ko if: prereqTo.length > 0 -->
        <span class="badge badge-important">!</span>
        <span data-bind="text: $root.i18n['delete_skill_dependency_warning_pre']"></span>
        <span data-bind="text: prereqTo.length"></span>
        <span data-bind="text: $root.i18n['delete_skill_dependency_warning_post']"></span>
      <!-- /ko -->
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal"><%= t :Cancel %></button>
    <button class="btn btn-danger" data-bind="click: clickConfirmDeletion"><%= t '.delete_skill' %></button>
  </div>
</div

app/views/curriculums/courses/skill_editor/_prereq_editor.html.erb
<div class="row-fluid full-height">

  <% content_for :searchable_column_heading do %>
    <%= t 'curriculums.courses.skill_editor.searchable_column.prereqs_column_heading' %>
  <% end %>

  <%= render 'curriculums/courses/skill_editor/searchable_column' %>

  <%= render 'curriculums/courses/skill_editor/current_course_column' %>

</div>

<!--p><%= link_to t(:Back), edit_curriculum_path(@curriculum) %></p-->

<%= render 'curriculums/courses/skill_editor/modals' %>

app/views/curriculums/courses/skill_editor/_searchable_column.html.erb
 <!-- Prereqs -->
  <div class="span6 full-height scroll-vertical">
    <!-- <h2><%=t '.prereqs_heading' %></h2> -->
    <h2><%= yield :searchable_column_heading %></h2>
    
    <div class="input-append bottom-weight">
      <input class="span8" type="text" id="search" placeholder="<%= t '.search_box_placeholder' %>" data-bind="value: searchString, valueUpdate: 'keyup', event: { keyup: searchKeyPress }" />
      <button class="btn" data-bind="click: clickSearch"><i class="icon-search"></i></button>
      <button class="btn" data-bind="click: clickClearSearch"><i class="icon-remove"></i></button>
    </div>
    
    <!-- Error alert box -->
    <div class="row-fluid hide" data-bind="css: { hide: loadFailed() === false }">
      <div class="alert alert-error span11">
        <strong><%= t 'curriculums.courses.skill_editor.load_failed_heading' %></strong> <%= t '.search_failure_message' %>
      </div>
    </div>

    <!-- loading icon -->
    <div class="skill-editor-loading-icon hide" data-bind="css: { hide: isLoading() === false }">
      <%= image_tag 'progress.gif' %>
    </div>

    <div data-bind="foreach: visibleNodes, css: { loading: skillBeingDeleted() }">
      <%= render :partial => 'curriculums/courses/skill_editor/competence_node', 
                 :locals => { :skills_sortable => false } %>
    </div>
  </div>

app/views/curriculums/courses/skill_editor/_skill_editor_i18n_strings.js.erb
/* Loads translated i18n strings used by skillEditor.js.coffee */
(function() {
  var i18n;

  /* Embeds translation parameter into translated string. */
  function deletion_failed_message(skill) {
    return i18n['deletion_failed_message_1'] + ' "' + skill + '" ' + i18n['deletion_failed_message_2'];
  };

  /* i18n strings */
  i18n = {
    current_locale:                 "<%= I18n.locale %>",
    required_locales:               ["<%= REQUIRED_LOCALES.join('","').html_safe %>"],
    competence:                     "<%= escape_javascript(t(:competence)) %>",
    scoped_course:                  "<%= escape_javascript(t(:scoped_course)) %>",

    language_in_fi:                 "<%= escape_javascript(t(:language_in_fi)) %>",
    language_in_sv:                 "<%= escape_javascript(t(:language_in_sv)) %>",
    language_in_en:                 "<%= escape_javascript(t(:language_in_en)) %>",
    
    delete_skill_no_dependencies:   "<%= escape_javascript(t('.delete_skill_no_dependencies')) %>",
    delete_skill_dependency_warning_pre:"<%= escape_javascript(t('.delete_skill_dependency_warning_pre')) %>",
    delete_skill_dependency_warning_post:"<%= escape_javascript(t('.delete_skill_dependency_warning_post')) %>",

    deletion_confirmation_question: "<%= escape_javascript(t('curriculums.courses.skill_editor.modals.deletion_confirmation_question')) %>",
    deletion_failed_heading:        "<%= escape_javascript(t('curriculums.courses.skill_editor.current_course_column.deletion_failed_heading')) %>",
    deletion_failed_message_1:      "<%= escape_javascript(t('curriculums.courses.skill_editor.current_course_column.deletion_failed_message_1')) %>",
    deletion_failed_message_2:      "<%= escape_javascript(t('curriculums.courses.skill_editor.current_course_column.deletion_failed_message_2')) %>",
    /* The following is a function! */
    deletion_failed_message: deletion_failed_message,

    saving_skill_failed_heading:    "<%= escape_javascript(t('curriculums.courses.skill_editor.current_course_column.saving_skill_failed_heading')) %>",
    saving_skill_failed_message:    "<%= escape_javascript(t('curriculums.courses.skill_editor.current_course_column.saving_skill_failed_message')) %>"
  };

  /* Translations available at O4.skillEditor.i18n */ 
  var O4 = window.O4 = window.O4 || {};
  O4.skillEditor = O4.skillEditor || {};
  O4.skillEditor.i18n = i18n;
})();