config/routes.rb
Ops::Application.routes.draw do
  scope ":locale" do
    resource :session do
      get 'shibboleth'
    end
    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout

    #match '/preferences' => 'users#edit'
#    resources :users, :only => [] do
#       member do
#         get :courses
#       end
#    end

    #resources :courses  # AbstractCourses
    #resources :course_instances, :only => [:index]
    #resources :skills

    # View study guides of other years
    resources :curriculums, :constraints => { :id => /\w+/ } do
      member do
        get 'graph'
        get 'search_skills'
        #get 'search_courses'
        match 'edit/import_csv', :controller => 'curriculums', :action => :import_csv, :via => [:post, :get]
      end

      resources :competence_nodes, :only => [], :controller => 'curriculums/competence_nodes' do
        collection do
          get 'nodes_by_skill_ids'
        end
      end

      resources :competences, :controller => 'curriculums/competences' do
        member do
          get 'graph'
          get 'courselist'
          get 'edit_prereqs'
        end
        
        resources :skills, :controller => 'curriculums/skills', :only => [:show]
        resources :courses, :controller => 'curriculums/courses', :only => [:show]
      end

      resources :courses, :controller => 'curriculums/courses' do  # ScopedCourses
        member do
          get 'edit_prereqs'
          get 'edit_as_a_prereq'
          get 'comments'
          post 'create_comment'
          get 'graph'
        end
      end

      resources :skills, :controller => 'curriculums/skills', :only => [:index, :create, :update, :destroy] do
        member do
          post 'add_prereq'
          post 'remove_prereq'
          put 'update_position'
        end
      end

      resources :roles, :controller => 'curriculums/roles', :only => [:new, :create, :destroy]
    end

    # My Plan
    resource :studyplan, :controller => 'plans', :only => [:show] do
      member do
        get :summary
      end
     
      resources :competences, :controller => 'plans/competences' do
        member do
          # get 'supporting'
          get 'delete'
        end
        
        resources :courses, :controller => 'plans/courses', :only => [:show, :create, :destroy] # show is obsolete
        resources :skills, :controller => 'plans/skills', :only => [:show]                      # obsolete
      end

      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]

      resource :schedule, :controller => 'plans/schedule', :only => [:show]

      resource :curriculum, :controller => 'plans/curriculums', :only => [:show, :edit, :update]
    end

    # Any plan (specify student ID)
    resources :plans, :constraints => { :id => /\w+/ }, :only => [:show, :update] do
      member do
        get :summary
      end
      
      get 'old_schedule', as: 'old_schedule'
      
      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]
#       resources :courses, :controller => 'plans/courses', :only => [:index, :show, :create]  # :except => [:edit, :update]
#       resource :schedule, :controller => 'plans/schedule', :only => [:show, :edit]
#       resource :record, :controller => 'plans/record', :only => [:show]
    end
    
    match 'search_courses' => "abstract_courses#search"
    resources :surveys, :only => [:show, :create], :constraints => { :id => /\w+/ }
  end

  resources :invitations, :only => [:show, :destroy], :id => /[^\/]+/

  #post 'client_side_error', :controller => 'application', as: 'client_side_error'
  match '/client_side_error' => 'application#client_side_error', as: 'client_side_error'
  match '/client_event', to: 'application#log_client_event', as: 'log_client_event'
  
  match '/:locale' => "frontpage#index", :as => :frontpage
  #root :to => "application#redirect_by_locale"
  root :to => "frontpage#index"

end

app/controllers/curriculums/competence_nodes_controller.rb
class Curriculums::CompetenceNodesController < CurriculumsController

  def nodes_by_skill_ids
    nodes_json = []
    
    if params[:ids]
      nodes = CompetenceNode.joins(:skills).where('skills.id' => params[:ids]).includes(:skills => [:skill_descriptions, :prereq_to]).uniq

      nodes_json = nodes.map do |node|
        if node.type == 'Competence'
          node.as_json(
            :only => [:id],
            :include => [
              {:skills => {
                  :only => [:id, :icon],
                  :include => {
                    :skill_descriptions => {
                      :only => [:id, :locale, :name]
                    },
                    :prereq_to => {:only => [:id, :requirement, :icon]}
                  }
              }},
              {:competence_descriptions => {
                  :only => [:id, :locale, :name, :description]
              }}
            ]
          )
        else 
          # Must be a ScopedCourse
          node.as_json(
            :only => [:id, :course_code],
            :include => [
              {:skills => {
                  :only => [:id, :icon],
                  :include => {
                    :skill_descriptions => {
                      :only => [:id, :locale, :name]
                    },
                    :prereq_to => {:only => [:id, :requirement, :icon]}
                  }
              }},
              {:course_descriptions => {
                  :only => [:id, :locale, :name]
              }}
            ]
          )
        end
      end
    end

    respond_to do |format|
      format.json { render :json => nodes_json, :root => false }
    end
  end


end

app/controllers/curriculums/competences_controller.rb
class Curriculums::CompetencesController < ApplicationController

  before_filter :load_competence, :only => [:edit, :edit_prereqs, :update, :graph, :courselist]
  
  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id] || params[:id])
  end
  
  def load_competence
    @competence = Competence.find(params[:competence_id] || params[:id])
    load_curriculum
  end

  def index
    load_curriculum
    @competences = Competence.where(:curriculum_id => @curriculum.id)
                    .joins(:competence_descriptions)
                    .where(["competence_descriptions.locale = ?", I18n.locale])

    respond_to do |format|
      format.json { render :json => @competences.select(<<-SQL
          competence_nodes.id,
          competence_descriptions.name AS translated_name
        SQL
      ).to_json(:methods => :strict_prereq_ids, :root => true) } # :skill_ids
    end
  end

  # curriculums/1/competences/1
  def show
    load_curriculum

    respond_to do |format|
      format.html {
        load_plan
    
        @competence = Competence.includes(:localized_description, {:skills => :localized_description}).find(params[:id])
        @chosen_competence_ids = @study_plan.competence_ids.to_set
        
        # Log
        @client_session_id = SecureRandom.hex(3)
        render :action => 'show', :layout => 'leftnav'
        log("view_competence #{@competence.id} (#{@client_session_id})")
      }

      format.json {
        @competence = Competence.includes(:skills => [:skill_descriptions, :skill_prereqs, :prereq_to]).find(params[:competence_id] || params[:id])
        render :json => @competence.to_json(
          :only => [:id],
          :include => {
              :skills => {
                :only => [:id, :icon],
                :include => {
                  :skill_descriptions => {
                    :only => [:id, :locale, :name]
                  },
                  :skill_prereqs => {:only => [:prereq_id, :requirement]}
                }
              },
              :competence_descriptions => {
                :only => [:id, :locale, :name]
              }
          },
          :root => true 
        )
      }
    end
  end

  # GET /competences/1/edit
  def edit
    authorize! :update, @competence

    # Add missing translations
    existing_locales = @competence.competence_descriptions.map {|description| description.locale}
    (REQUIRED_LOCALES - existing_locales).map do |locale|
      existing_locales = @competence.competence_descriptions << CompetenceDescription.new(:competence => @competence, :locale => locale, :name => '', :term_id => @curriculum.term_id)
    end

    render :action => 'edit', :layout => 'views/curriculums/container'
  end


  def edit_prereqs
    #@competence = Competence.find(params[:id])
    @competence_node = @competence
    authorize! :update, @competence

    @hide_help = cookies[:hide_edit_competence_prereqs_help] == 't' ? true : false

    @competence_node_url = curriculum_competence_path(:curriculum_id => @curriculum, :competence_id => @competence)

    render :action => 'edit_prereqs', :layout => 'views/curriculums/container'
  end

  # PUT /competences/1
  # PUT /competences/1.xml
  def update
    authorize! :update, @competence
    @curriculum.save  # Expire cache

    respond_to do |format|
      if @competence.update_attributes(params[:competence])
        format.html { redirect_to edit_curriculum_path(@curriculum) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def new
    load_curriculum
    @competence = Competence.new(:curriculum => @curriculum)

    authorize! :update, @curriculum

    REQUIRED_LOCALES.each do |locale|
      @competence.competence_descriptions << CompetenceDescription.new(:competence => @competence, :locale => locale, :term_id => @curriculum.term_id)
    end
    
    render :action => 'new', :layout => 'views/curriculums/browser'
  end

  def create
    load_curriculum
    authorize! :update, @curriculum
    @curriculum.save  # Expire cache
    
    @competence = Competence.new(params[:competence])
    @competence.term = @curriculum.term

    respond_to do |format|
      if @competence.save
        format.html { redirect_to(edit_curriculum_path(@curriculum), :notice => 'Competence was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def graph
    #@competence = Competence.find(params[:id])

    render :action => 'graph', :layout => 'views/curriculums/container'
  end
  
  def courselist
    #@competence = Competence.find(params[:id])
    
    render :action => 'courselist', :layout => 'views/curriculums/container'
  end
end

app/controllers/curriculums/roles_controller.rb
class Curriculums::RolesController < CurriculumsController
  before_filter :login_required
  before_filter :load_curriculum
  
  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id])
    authorize! :update, @curriculum
  end
  
  def new
    @invitations = TeacherInvitation.where(:target_id => @curriculum.id).all
    @subject = t("curriculums.roles.new.subject_default")
    @content = t("curriculums.roles.new.mail_template")
  end
  
  def create
    unless params[:addresses].blank?
      Curriculum.delay.invite_teachers(@curriculum.id, params[:addresses].split(/[,\s]/), params[:subject], params[:content])
    end
    
    #render :action => :new
    flash[:success] = t('curriculums.roles.new.sent_success')
    redirect_to curriculum_path(@curriculum)
  end
  
  def destroy
    user = User.find(params[:id])
    
    CurriculumRoles.where(:user_id => user.id, :target_id => @curriculum.id, :role => 'teacher').delete
    
    respond_to do |format|
      #format.html { redirect_to course_teachers_path(@course) }
      format.json { render :json => [user.id].as_json }
    end
  end
end
 

app/controllers/plans/competences_controller.rb
require 'set'

class Plans::CompetencesController < PlansController

  def index
    # OBSOLETE
    authorize! :read, @study_plan
    
    log("view_competences")
    @competences = @curriculum.competences.joins(:competence_descriptions).includes(:localized_description, :skills => [:localized_description]).where(:parent_competence_id => nil, :competence_descriptions => {:locale => I18n.locale}) .order('competence_descriptions.name')
    @chosen_competence_ids = @study_plan.competence_ids.to_set

    render :action => :index, :layout => 'fixed'
  end

  # GET /plans/1/competence/1
  # GET /plans/1/competence/1.xml
  def show
    # OBSOLETE
    authorize! :read, @study_plan
    
    @competence = Competence.includes(:localized_description, {:skills => :localized_description}).find(params[:id])
    @chosen_competence_ids = @study_plan.competence_ids.to_set
    
    # Log
    @client_session_id = SecureRandom.hex(3)
    log("view_competence #{@competence.id} (#{@client_session_id})")
    
    render :action => 'show', :layout => 'leftnav'
    
    #@mandatory_courses = @competence.recursive_prereq_courses.includes(:localized_description).all
    #@mandatory_prereqs = @competence.ancestor_prereq_courses.includes(:localized_description).all - @mandatory_courses
    #@supporting_courses = @competence.supporting_prereq_courses.includes(:localized_description).order(:course_code).all - @mandatory_courses
    #@included_courses = @study_plan.scoped_course_ids.to_set
    
    # @passed_courses = Hash.new
    # @study_plan.passed_courses.each do |course|
    #   @passed_courses[course.id] = course
    # end
  end

  # Prepare to add competence to study plan
  def new
    authorize! :update, @study_plan
    
    @competence_node = CompetenceNode.find(params[:id])
    #authorize! :choose, @competence_node
    
    # If competence is aleady in the plan, don't do anything
    if @study_plan.has_competence?(@competence_node)
      if @competence_node.is_a? Competence
        redirect_to studyplan_competence_path(:id => @competence_node)
      elsif @competence_node.is_a? ScopedCourse
        redirect_to studyplan_course_path(:id => @competence_node)
      end
      return
    end

    # FIXME: plan may contain PlanCourses that are not associated with a ScopedCourse
    existing_courses = @study_plan.scoped_courses
    prereqs = @competence_node.recursive_prereq_courses.includes(:localized_description).all
    @new_courses = prereqs - existing_courses # difference
    @shared_courses = existing_courses & prereqs # intersection
    
    render :action => 'new', :layout => 'fixed'
    
    log("add_competence prepare #{@competence_node.id}")
  end

  # Adds a competence to the study plan
  # POST /plans/1/profiles
  # POST /plans/1/profiles.xml
  def create
    authorize! :update, @study_plan
    competence = Competence.find(params[:competence_id])
    authorize! :choose, competence

    log("add_competence_commit #{competence.id}")
    
    # Dont't do anything if user has already selected this competence
    if @study_plan.has_competence?(params[:competence_id])
      redirect_to curriculum_competence_path(curriculum_id: competence.curriculum_id, id: competence), :flash => {:error => t('.competence_already_selected', :name => @competence.localized_name)}
    end

    # Add competence to study plan
    @study_plan.add_competence(competence)

    redirect_to curriculum_competence_path(curriculum_id: competence.curriculum_id, id: competence)
  end

  def delete
    authorize! :update, @study_plan
    @competence = Competence.find(params[:id])

    log("remove_competence_prepare #{@competence.id}")
    
    @courses = @study_plan.deletable_scoped_courses(@competence)
  end

  # Removes a profile from the study plan
  # DELETE /plans/1/profiles/1
  # DELETE /plans/1/profiles/1.xml
  def destroy
    authorize! :update, @study_plan
    competence = Competence.find(params[:id])

    @study_plan.remove_competence(competence)
    log("remove_competence_commit #{competence.id}")

    respond_to do |format|
      format.html { redirect_to curriculum_competence_path(curriculum_id: competence.curriculum_id, id: competence) }
    end
  end

  def supporting
    authorize! :read, @study_plan
    
    @competence = Competence.includes(
                    :courses,
                    :courses => {
                      :skills => [
                        :supporting_prereqs,
                        { :supporting_prereqs => :competence_node }
                      ]
                    }).find(params[:id])
    log("view_competence_supporting #{@competence.id}")

    @supporting_courses = {}  # scoped_course_id => credits

    @competence.courses.each do |course|
      course.skills.each do |skill|
        skill.supporting_prereqs.each do |supporting_skill|

          competence_node = supporting_skill.competence_node

          @supporting_courses[competence_node] ||= 0.0
          @supporting_courses[competence_node] += supporting_skill.credits
        end
      end
    end
  end

end

app/controllers/plans/curriculums_controller.rb
class Plans::CurriculumsController < PlansController

  before_filter :authenticate_user
  before_filter :load_plan, :only => :show

  # Make sure 'redirect_to' value is not saved here, because edit page uses it for redirect!
  skip_before_filter :store_location

  layout 'fixed'
  
  def show
    authorize! :read, @user
    
    # Store 'redirect_to' address so that cancel button works on edit page
    store_location
  end

  def edit
    @user = current_user
    authorize! :update, @user
    @curriculums = Curriculum.order(:start_year)
  end

  def update
    @user = current_user
    authorize! :update, @user
    
    if params[:user_study_plan]
      if @user.study_plan
        @user.study_plan.save
      else
        @user.create_study_plan()
      end
    end
    
    redirect_to studyplan_competences_path
  end

end

app/helpers/competences_helper.rb
module CompetencesHelper

end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/competences/_prereq_skills_selection.html.erb
<div>
  <div class="info">
    <strong>Ohje</strong>
    Täällä voit lisätä esitietovaatimuksia valitsemallesi valmiudelle.
    Käytä hakukenttää esitietovaatimusten etsimiseen.
  </div>

  <strong>Valittu valmius:</strong> <%= @skill.description_with_locale.description %>

  <div id="metadata" style="display: none" 
    data-skill-id="<%= @skill_id %>"
    data-skill-search-url="<%= 
      search_skills_and_courses_curriculum_competence_path(params[:locale], 
        params[:curriculum_id], params[:id]) %>"
    data-skill-prereq-add-url="<%= add_prereq_skill_path(params[:locale], 
      @skill_id) %>"
    data-skill-prereq-remove-url="<%= remove_prereq_skill_path(params[:locale], 
      @skill_id) %>"
    data-prereq-add-text="<%= t :competence_skill_add_prereq_button %>"
    data-prereq-adding-text="<%= t :competence_skill_add_prereq_button_adding %>"
    data-prereq-remove-text="<%= t :competence_skill_add_prereq_button_remove %>"
    data-prereq-removing-text="<%= t :competence_skill_add_prereq_button_removing %>">
  </div>

  <h4 class="colorful">Nykyiset vaatimukset</h4>

  <div>
    <table id="skill-current-prereqs">
      <% @courses_rendered.each do |course| %>
        <%# The html code must not be escaped %>
        <%= raw(course) %>
      <% end %>
    </table>
  </div>

  <h4 class="colorful">Lisää uusia vaatimuksia</h4>

  <p>Hae kursseja ja niiden valmiuksia</p>  

  <input id="skill-search-box"></input>

  <div id="skill-search-results">

  </div>

  <div id="skill-endless-pagination-footer">
      <p>
        <span id="skill-endless-pagination-hint" class="hide">
          <%= t :competence_skill_search_footer_hint %>
        </span>
        <span id="skill-endless-pagination-no-results-msg" class="hide">
          <%= t :competence_skill_search_footer_no_results %>
        </span>
        <span id="skill-endless-pagination-failure-msg" class="hide">
          <%= t :competence_skill_search_footer_failure %>
        </span>
      </p>
      <p>
        <span id="skill-endless-pagination-loading" class="hide"><%= image_tag "progress.gif" %></span>
      </p>
  </div>

     
</div>

app/views/curriculums/competences/_tabs.html.erb
<ul class="nav nav-pills pull-right">
  <li class="active"><%= link_to t('Admin_view'), edit_prereqs_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li>
  <li><%= link_to t('Student_view'), curriculum_competence_path(curriculum_id: @curriculum, id: @competence) %></li>
</ul>
  
<div>
  <h1>
    <%= link_to @curriculum.name, edit_curriculum_path(@curriculum) %> /
    <%= @competence.localized_name %>
  </h1>
</div>

<ul class="nav nav-tabs">
  <li<%= controller.action_name == 'edit' ? ' class="active"'.html_safe : '' %>><%= link_to t('curriculums.competences.edit_tab'), edit_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li>
  <li<%= controller.action_name == 'edit_prereqs' ? ' class="active"'.html_safe : '' %>><%= link_to t('curriculums.competences.prereqs_tab'), edit_prereqs_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li>
  <li<%= controller.action_name == 'graph' ? ' class="active"'.html_safe : '' %>><%= link_to t('curriculums.competences.graph_tab'), graph_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li>
  <!--li<%= controller.action_name == 'courselist' ? ' class="active"'.html_safe : '' %>><%= link_to t('curriculums.competences.courselist_tab'), courselist_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li-->
  
  <% if controller.action_name == 'edit_prereqs' || controller.action_name == 'edit_as_a_prereq' %>
    <!-- ko with: hintViewModel -->
      <li>
        <button class="btn btn-mini btn-info" 
                type="button" 
                data-bind="toggle: shown">
          <%= t 'curriculums.show_help' %>
        </button>
      </li>
    <!-- /ko -->
  <% end %>
</ul>

app/views/curriculums/competences/graph.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'views/curriculums/courseGraph' %>
<% end %>

<% content_for :title do %>
  <%= @competence.localized_name + ' - ' + t('.title') %>
<% end %>


<%= render :partial => 'tabs' %>

<div id="course-graph" class="course-graph"
    data-graph-path="<%= graph_curriculum_path(:id => @curriculum.id) %>"
    data-source-id="<%= @competence.id %>"
    >
    
    <!-- ko template: { name: 'courseTemplate', foreach: visibleCourses, afterRender: updateElementDimensions } --><!-- /ko -->
</div>

<%= render :partial => 'courses/graph_templates' %>

app/views/curriculums/competences/prereqs.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'raphael-min' %>
  <%= javascript_include_tag 'skillGraphView' %>
  <%= javascript_include_tag 'graphCourse' %>
  <%= javascript_include_tag 'graphSkill' %>
<% end %>

<!--%= link_to t(:Back), curriculum_competence_path(:curriculum_id => @curriculum.id, :id => @competence.id) %-->

<div id="layers">
  <div id="svg"></div>
  <div id="course-graph" 
    data-course-id="<%= @competence.id %>" 
    data-courses-path="<%= curriculum_courses_path(:curriculum_id => @curriculum.id) %>" 
    data-competences-path="<%= curriculum_competences_path(:curriculum_id => @curriculum.id) %>" 
    data-skills-path="<%= curriculum_skills_path(:curriculum_id => @curriculum.id) %>">
  </div>
</div>

app/views/curriculums/competences/show.html.erb
<!-- curriculums/competences/show -->
<% content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag "views/plans/competences/shared", :media => 'all' %>
<% end -%>
<% content_for(:javascripts) do -%>
  <%= javascript_tag do %>
    window.studyplan_summary_data = <%= @study_plan.json_summary.to_json( root: false ).html_safe %>;
    window.client_session_id = '<%= @client_session_id %>';
  <% end %>
  <%= javascript_include_tag 'views/plans/competences/show' %>
<% end -%>

<% content_for(:leftnav) do -%>
  <h1><%= link_to t('.competences'), curriculum_path(@curriculum) %></h1>
  <ul>
    <% @curriculum.competences.joins(:competence_descriptions).where(:parent_competence_id => nil, :competence_descriptions => {:locale => I18n.locale}).includes(:localized_description).order('competence_descriptions.name').each do |competence| %>
      <li class="<%= @chosen_competence_ids.member?(competence.id) ? 'chosen' : '' %> <%= competence == @competence ? 'selected' : '' %>">
        <%= link_to competence.localized_name, curriculum_competence_path(:curriculum_id => @curriculum, :id => competence) %>
      </li>
    <% end %>
  </ul>
<% end -%>

<% if can? :update, @competence %>
  <ul class="nav nav-pills pull-right">
    <li><%= link_to t('Admin_view'), edit_prereqs_curriculum_competence_path(:curriculum_id => @curriculum, :id => @competence) %></li>
    <li class="active"><%= link_to t('Student_view'), curriculum_competence_path(curriculum_id: @curriculum, id: @competence) %></li>
  </ul>
  <div class="clearfix"></div>
<% end %>

<% competence_selected = @study_plan.has_competence?(@competence) %>

<div class="well competence<%= competence_selected ? ' selected' : '' %>">
  <!-- Add / Remove -->
  <div class="pull-right">
    <% if can? :choose, @competence %>
      <% if @study_plan.has_competence?(@competence) %>
        <%= link_to delete_studyplan_competence_path(:id => @competence.id), {:title => t('.remove_from_plan'), :class => 'btn btn-default'} do %>
          <i class="icon icon-minus"></i>
          <%= t('.remove_from_plan') %>
        <% end %>
      <% else %>
        <%= link_to new_studyplan_competence_path(:id => @competence.id), {:title => t('.add_to_plan'), :class => 'btn btn-default'} do %>
          <i class="icon icon-plus"></i>
          <%=t ('.add_to_plan') %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%
  # cache("competence_details-#{@competence.id}") do # FIXME: language
  -%>
    <h2>
      <%= @competence.localized_name %>
      <% if @competence.min_credits %>(<%= @competence.min_credits %> <%=t 'cr' %>)<% end %>
    </h2>

    <!-- Description -->
    <div class="row-fluid">
      <div class="span12">
        <% if @competence.localized_description && !@competence.localized_description.description.blank? %>
          <%= @competence.localized_description.description.html_safe %>
        <% end %>
      </div>
    </div>
    
    <div class="row-fluid">
      <!-- Learning outcomes -->
      <div class="span6">
        <h3><%= t('.skills') %></h3>
        <ul>
          <% @competence.skills.each do |skill| %>
            <li><%= link_to skill.localized_name, curriculum_competence_skill_path(:curriculum_id => @curriculum, :competence_id => @competence, :id => skill) %></li>
          <% end %>
        </ul>
        
        <p class="hint"><%=t '.skills_hint' %></p>
      </div>
      
      <!-- Courses -->
      <div class="span6">
        <!-- Mandatory courses -->
        <% mandatory_courses = @competence.recursive_prereq_courses.includes(:localized_description) %>
        <% unless mandatory_courses.empty? %>
          <h3><%= t('.strict_prereqs') %></h3>
          <%= render :partial => 'course_table', :locals => { :course_list => mandatory_courses, :competence => @competence, :top_competence => @competence } %>
        <% end %>
        
        <!-- Child competences -->
        <% @competence.children.includes(:localized_description).each do |child_competence| %>
          <div class="child-competence">
            <% if child_competence.localized_description %>
              <h3>
                <%= child_competence.localized_description.name %>
                <% if child_competence.min_credits %>(<%= child_competence.min_credits %> <%=t 'cr' %>)<% end %>
              </h3>
              <p><%= child_competence.localized_description.description %></p>
            <% end %>
            
            <%= render :partial => 'course_table', :locals => { :course_list => child_competence.supporting_prereq_courses.includes(:localized_description), :competence => child_competence, :top_competence => @competence } %>
          </div>
        <% end %>
      
        <hr />
      
        <div class="total-credits">
          <p class="total">
            <%=t '.total_credits' %>
            <span class="number" id="total-credits"><%= image_tag 'progress.gif' %></span>&nbsp;<span><%=t :cr %></span>
          </p>
          
          <p class="hint"><%=t '.total_credits_hint' %></p>
        </div>
        
        <% if current_user %>
          <p>
            <em><%=t '.curriculums.competences.course_table.legend' %>:</em>
          </p>
          <table>
            <tr>
              <td style="vertical-align: top"><i class="icon icon-asterisk"></i></td>
              <td><em><%=t '.curriculums.competences.course_table.included_here' %></em></td>
            </tr>
            <tr>
              <td style="vertical-align: top">&bull;</td>
              <td><em><%=t '.curriculums.competences.course_table.included_elsewhere' %></em></td>
            </tr>
        <% end %>
        </table>
      </div>
    </div>
  <% # end # cache
  -%>
</div>

<!-- Graph -->
<h2 class="inline-heading"><%=t :Course_graph %></h2>
<%= hint_button :dynamic_course_graph_hint %>

<%= render :partial => 'courses/graph_templates' %>

<div id="course-graph" class="course-graph"
  data-graph-path="<%= graph_curriculum_path(:id => @curriculum.id) %>" 
  data-source-id="<%= @competence.id %>"
  >

  <!-- ko template: { name: 'courseTemplate', foreach: visibleCourses, afterRender: updateElementDimensions } --><!-- /ko -->
</div>