config/routes.rb
Ops::Application.routes.draw do
  scope ":locale" do
    resource :session do
      get 'shibboleth'
    end
    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout

    #match '/preferences' => 'users#edit'
#    resources :users, :only => [] do
#       member do
#         get :courses
#       end
#    end

    #resources :courses  # AbstractCourses
    #resources :course_instances, :only => [:index]
    #resources :skills

    # View study guides of other years
    resources :curriculums, :constraints => { :id => /\w+/ } do
      member do
        get 'graph'
        get 'search_skills'
        #get 'search_courses'
        match 'edit/import_csv', :controller => 'curriculums', :action => :import_csv, :via => [:post, :get]
      end

      resources :competence_nodes, :only => [], :controller => 'curriculums/competence_nodes' do
        collection do
          get 'nodes_by_skill_ids'
        end
      end

      resources :competences, :controller => 'curriculums/competences' do
        member do
          get 'graph'
          get 'courselist'
          get 'edit_prereqs'
        end
        
        resources :skills, :controller => 'curriculums/skills', :only => [:show]
        resources :courses, :controller => 'curriculums/courses', :only => [:show]
      end

      resources :courses, :controller => 'curriculums/courses' do  # ScopedCourses
        member do
          get 'edit_prereqs'
          get 'edit_as_a_prereq'
          get 'comments'
          post 'create_comment'
          get 'graph'
        end
      end

      resources :skills, :controller => 'curriculums/skills', :only => [:index, :create, :update, :destroy] do
        member do
          post 'add_prereq'
          post 'remove_prereq'
          put 'update_position'
        end
      end

      resources :roles, :controller => 'curriculums/roles', :only => [:new, :create, :destroy]
    end

    # My Plan
    resource :studyplan, :controller => 'plans', :only => [:show] do
      member do
        get :summary
      end
     
      resources :competences, :controller => 'plans/competences' do
        member do
          # get 'supporting'
          get 'delete'
        end
        
        resources :courses, :controller => 'plans/courses', :only => [:show, :create, :destroy] # show is obsolete
        resources :skills, :controller => 'plans/skills', :only => [:show]                      # obsolete
      end

      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]

      resource :schedule, :controller => 'plans/schedule', :only => [:show]

      resource :curriculum, :controller => 'plans/curriculums', :only => [:show, :edit, :update]
    end

    # Any plan (specify student ID)
    resources :plans, :constraints => { :id => /\w+/ }, :only => [:show, :update] do
      member do
        get :summary
      end
      
      get 'old_schedule', as: 'old_schedule'
      
      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]
#       resources :courses, :controller => 'plans/courses', :only => [:index, :show, :create]  # :except => [:edit, :update]
#       resource :schedule, :controller => 'plans/schedule', :only => [:show, :edit]
#       resource :record, :controller => 'plans/record', :only => [:show]
    end
    
    match 'search_courses' => "abstract_courses#search"
    resources :surveys, :only => [:show, :create], :constraints => { :id => /\w+/ }
  end

  resources :invitations, :only => [:show, :destroy], :id => /[^\/]+/

  #post 'client_side_error', :controller => 'application', as: 'client_side_error'
  match '/client_side_error' => 'application#client_side_error', as: 'client_side_error'
  match '/client_event', to: 'application#log_client_event', as: 'log_client_event'
  
  match '/:locale' => "frontpage#index", :as => :frontpage
  #root :to => "application#redirect_by_locale"
  root :to => "frontpage#index"

end

app/controllers/surveys_controller.rb
# encoding: UTF-8
class SurveysController < ApplicationController
  before_filter :authenticate_user
  before_filter :load_plan

  layout 'views/surveys'
  
  def load_plan
    @user = current_user

    @study_plan = @user.study_plan
    unless @study_plan
      log('survey_error no studyplan')
      redirect_to root_url
      return false
    end

    @curriculum = @user.study_plan.curriculum
  end
  
  def show
    # if SurveyAnswer.exists?(:user_id => @user.id)
    #   redirect_to root_url
    #   return
    # end

    @survey_id = @user.treatment
    chosen_competence_ids = @study_plan.competence_ids
    chosen_course_ids = @study_plan.scoped_course_ids
    
    if chosen_competence_ids.include?(73) # ENY
      @major_name = 'Energia- ja ympäristötekniikan'
      @major_id = 73
      @usefulness_questions = [
        {:id => 9, :course_code => 'PHYS-A3120', :name => 'Termodynamiikka (ENG)'},
        {:id => 44, :course_code => 'KJR-C2004', :name => 'Materiaalitekniikka'},
        {:id => 66, :course_code => 'YYT-C2001', :name => 'Hydrologian ja hydrauliikan perusteet'},
        {:id => 13, :course_code => 'MS-A030x', :name => 'Differentiaali- ja integraalilaskenta 3'}
      ]
      @motivation_questions = [
        {:id => 9, :course_code => 'PHYS-A3120', :name => 'Termodynamiikka (ENG)'},
        {:id => 44, :course_code => 'KJR-C2004', :name => 'Materiaalitekniikka'}
      ]
      @motivation_questions << {:id => 66, :course_code => 'YYT-C2001', :name => 'Hydrologian ja hydrauliikan perusteet'} if chosen_course_ids.include?(66)
      @motivation_questions << {:id => 13, :course_code => 'MS-A030x', :name => 'Differentiaali- ja integraalilaskenta 3'} if chosen_course_ids.include?(13)
      
    elsif chosen_competence_ids.include?(59) # KJR
      @major_name = 'Kone- ja rakennustekniikan'
      @major_id = 59
      @usefulness_questions = [
        {:id => 9, :course_code => 'PHYS-A3120', :name => 'Termodynamiikka (ENG)'},
        {:id => 4, :course_code => 'KJR-C2001', :name => 'Kiinteän aineen mekaniikan perusteet'},
        {:id => 13, :course_code => 'MS-A030x', :name => 'Differentiaali- ja integraalilaskenta 3'},
        {:id => 52, :course_code => 'KON-C3001', :name => 'Koneenrakennustekniikka A'}
        # {:id => 6, :course_code => 'ENY-C2001', :name => 'Termodynamiikka ja lämmönsiirto'},
        # {:id => 12, :course_code => 'MS-A020x', :name => 'Differentiaali- ja integraalilaskenta 2'},
        # {:id => 49, :course_code => 'RAK-C3003', :name => 'Tietoyhdennetty rakentaminen'},
        # {:id => 48, :course_code => 'KON-C3004', :name => 'Kone- ja rakennustekniikan laboratoriotyö'}
      ]
      
      @motivation_questions = [
        {:id => 9, :course_code => 'PHYS-A3120', :name => 'Termodynamiikka (ENG)'},
        {:id => 4, :course_code => 'KJR-C2001', :name => 'Kiinteän aineen mekaniikan perusteet'},
        {:id => 13, :course_code => 'MS-A030x', :name => 'Differentiaali- ja integraalilaskenta 3'}
        #{:id => 6, :course_code => 'ENY-C2001', :name => 'Termodynamiikka ja lämmönsiirto'},
        #{:id => 12, :course_code => 'MS-A020x', :name => 'Differentiaali- ja integraalilaskenta 2'},
      ]
      @motivation_questions << {:id => 52, :course_code => 'KON-C3001', :name => 'Koneenrakennustekniikka A'} if chosen_course_ids.include?(52)
      # @motivation_questions << {:id => 49, :course_code => 'RAK-C3003', :name => 'Tietoyhdennetty rakentaminen'} if chosen_course_ids.include?(49)
      # @motivation_questions << {:id => 48, :course_code => 'KON-C3004', :name => 'Kone- ja rakennustekniikan laboratoriotyö'} if chosen_course_ids.include?(48)

    elsif chosen_competence_ids.include?(74) # RYM
      @major_name = 'Rakennetun ympäristön (RYM)'
      @major_id = 74
      
      @usefulness_questions = [
        {:id => 15, :course_code => 'MS-A050x', :name => 'Todennäköisyyslaskennan ja tilastotieteen peruskurssi'},
        {:id => 35, :course_code => 'PHYS-A3130', :name => 'Sähkömagnetismi (ENG)'},
        {:id => 98, :course_code => 'MAA-C2003', :name => 'Kiinteistötekniikan perusteet'},
        {:id => 12, :course_code => 'MS-A020x', :name => 'Differentiaali- ja integraalilaskenta 2'}
      ]
      @motivation_questions = [
        {:id => 15, :course_code => 'MS-A050x', :name => 'Todennäköisyyslaskennan ja tilastotieteen peruskurssi'},
        {:id => 35, :course_code => 'PHYS-A3130', :name => 'Sähkömagnetismi (ENG)'}
      ]
      @motivation_questions << {:id => 98, :course_code => 'MAA-C2003', :name => 'Kiinteistötekniikan perusteet'} if chosen_course_ids.include?(98)
      @motivation_questions << {:id => 12, :course_code => 'MS-A020x', :name => 'Differentiaali- ja integraalilaskenta 2'} if chosen_course_ids.include?(12)
      
    else
      # No major selected
      @major_name = ''
      @major_id = 0
      @usefulness_questions = []
      @motivation_questions = []
    end
    
    case @user.treatment
    when TREATMENT_GRAPH
      render :action => 'treatment'
    when TREATMENT_TRADITIONAL
      render :action => 'control'
    else
      redirect_to studyplan_competences_path()
    end
    
    log("survey view")
  end
  
  def create
    @answers = SurveyAnswer.new
    
    @answers.user = current_user
    @answers.studentnumber = current_user.studentnumber
    @answers.login = current_user.login
    @answers.survey_id = params[:survey_id]
    @answers.payload = (params[:questions] || {}).to_json
    @answers.save
    
    @user.treatment += 2
    @user.save(:validate => false)
    
    flash[:success] = 'Kiitos osallistumisestasi tutkimukseen!'
    redirect_to studyplan_competences_path()
    
    log("survey answer")
  end

end

app/views/surveys/completed.html.erb
<h1>Kiitos vastauksesta</h1> 

app/views/surveys/control.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag "views/surveys", :media => 'all' %>
<% end %>

<h1>Kyselytutkimus</h1>

<p>Selvitämme tällä kyselyllä O<sub>4</sub>-järjestelmän toimivuutta perinteisiin opinto-oppaisiin verrattuna. Vastaamalla kyselyyn annat suostumuksesi siihen, että vastauksiasi käytetään tutkimustarkoituksiin. Vastaukset käsitellään luottamuksellisesti ja tutkimuksen tulokset raportoidaan niin, ettei yksittäistä vastaajaa pysty tunnistamaan.</p>

<p>Osallistumalla tutkimukseen autat meitä kehittämään tätä järjestelmää ja opintojen ohjausta eteenpäin, joten vastauksesi on meille erittäin tärkeä.</p>

<hr />

<%= form_tag surveys_path, :class => '' do |f| %>
  <%= hidden_field_tag :survey_id, @survey_id %>
  <%= hidden_field_tag 'questions[major-id]', @major_id %>

  <!-- Motivation -->
  <div class="surveyquestion">
    <p>Kuinka motivoitunut olet suorittamaan seuraavia kursseja?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>En lainkaan motivoitunut</td>
          <td>En kovin motivoitunut</td>
          <td>Melko motivoitunut</td>
          <td>Hyvin motivoitunut</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @motivation_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!-- Interest -->
  <div class="surveyquestion">
    <p>Kuinka kiinnostavina pidät seuraavia kursseja?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>En lainkaan kiinnostunut</td>
          <td>En kovin kiinnostunut</td>
          <td>Melko kiinnostunut</td>
          <td>Hyvin kiinnostunut</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @usefulness_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!-- Usefulness -->
  <div class="surveyquestion">
    <p>Kuinka keskeisiä seuraavat kurssit ovat mielestäsi <em><%= @major_name %></em> osaamisen kannalta?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>Ei lainkaan keskeinen</td>
          <td>Ei kovin keskeinen</td>
          <td>Melko keskeinen</td>
          <td>Hyvin keskeinen</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @usefulness_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <p>
    <label class="control-label" for="valinnaiset">Millä perusteella valitsit valinnaisia kursseja?</label>
    <textarea id="valinnaiset" name="questions[valinnaiset]" class="span6" rows="4"></textarea>
  </p>
  
  <p>
    <label class="control-label" for="jatkokehitys">Mitä puutteita havaitsit järjestelmässä? Miten kehittäisit sitä eteenpäin?</label>
    <textarea id="jatkokehitys" name="questions[jatkokehitys]" class="span6" rows="4"></textarea>
  </p>

  <p><%= submit_tag 'Lähetä', :class => 'btn btn-primary' %></p>
<% end %>

app/views/surveys/treatment.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag "views/surveys", :media => 'all' %>
<% end %>

<h1>Kyselytutkimus</h1>

<p>Selvitämme tällä kyselyllä O<sub>4</sub>-järjestelmän toimivuutta perinteisiin opinto-oppaisiin verrattuna. Vastaamalla kyselyyn annat suostumuksesi siihen, että vastauksiasi käytetään tutkimustarkoituksiin. Vastaukset käsitellään luottamuksellisesti ja tutkimuksen tulokset raportoidaan niin, ettei yksittäistä vastaajaa pysty tunnistamaan.</p>

<p>Osallistumalla tutkimukseen autat meitä kehittämään tätä järjestelmää ja opintojen ohjausta eteenpäin, joten vastauksesi on meille erittäin tärkeä.</p>

<hr />

<%= form_tag surveys_path, :class => '' do |f| %>
  <%= hidden_field_tag :survey_id, @survey_id %>
  <%= hidden_field_tag 'questions[major-id]', @major_id %>

  <!-- Motivation -->
  <div class="surveyquestion">
    <p>Kuinka motivoitunut olet suorittamaan seuraavia kursseja?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>En lainkaan motivoitunut</td>
          <td>En kovin motivoitunut</td>
          <td>Melko motivoitunut</td>
          <td>Hyvin motivoitunut</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @motivation_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-motivation]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!-- Interest -->
  <div class="surveyquestion">
    <p>Kuinka kiinnostavina pidät seuraavia kursseja?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>En lainkaan kiinnostunut</td>
          <td>En kovin kiinnostunut</td>
          <td>Melko kiinnostunut</td>
          <td>Hyvin kiinnostunut</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @usefulness_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-interest]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!-- Usefulness -->
  <div class="surveyquestion">
    <p>Kuinka keskeisiä seuraavat kurssit ovat mielestäsi <em><%= @major_name %></em> osaamisen kannalta?</p>
    <table class="survey">
      <thead>
        <tr>
          <td class="course-name"></td>
          <td>Ei lainkaan keskeinen</td>
          <td>Ei kovin keskeinen</td>
          <td>Melko keskeinen</td>
          <td>Hyvin keskeinen</td>
          <td class="eos">En osaa sanoa</td>
        </tr>
      </thead>
      <tbody>
        <% @usefulness_questions.each_with_index do |question, index| %>
          <tr class="<%= index % 2 == 0 ? 'even' : 'odd' %>">
            <td class="course-name"><%= question[:course_code] %> <%= question[:name] %></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="1"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="2"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="3"></td>
            <td><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="4"></td>
            <td class="eos"><input type="radio" name="questions[course-<%= question[:id] %>-usefulness]" value="-"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <p>
    <label class="control-label" for="valinnaiset">Millä perusteella valitsit valinnaisia kursseja?</label>
    <textarea id="valinnaiset" name="questions[valinnaiset]" class="span6" rows="4"></textarea>
  </p>
  
  <p>
    <label class="control-label" for="verkot">Kuinka käytit kurssiverkkoja? Vaikuttivatko ne opintojesi suunnitteluun?</label>
    <textarea id="verkot" name="questions[verkot]" class="span6" rows="4"></textarea>
  </p>
  
  <p>
    <label class="control-label" for="jatkokehitys">Mitä puutteita havaitsit järjestelmässä? Miten kehittäisit sitä eteenpäin?</label>
    <textarea id="jatkokehitys" name="questions[jatkokehitys]" class="span6" rows="4"></textarea>
  </p>

  <p><%= submit_tag 'Lähetä', :class => 'btn btn-primary' %></p>
<% end %>