config/routes.rb
Ops::Application.routes.draw do
  scope ":locale" do
    resource :session do
      get 'shibboleth'
    end
    match '/login' => 'sessions#new', :as => :login, :via => :get
    match '/login' => 'sessions#create', :via => :post
    match '/logout' => 'sessions#destroy', :as => :logout

    #match '/preferences' => 'users#edit'
#    resources :users, :only => [] do
#       member do
#         get :courses
#       end
#    end

    #resources :courses  # AbstractCourses
    #resources :course_instances, :only => [:index]
    #resources :skills

    # View study guides of other years
    resources :curriculums, :constraints => { :id => /\w+/ } do
      member do
        get 'graph'
        get 'search_skills'
        #get 'search_courses'
        match 'edit/import_csv', :controller => 'curriculums', :action => :import_csv, :via => [:post, :get]
      end

      resources :competence_nodes, :only => [], :controller => 'curriculums/competence_nodes' do
        collection do
          get 'nodes_by_skill_ids'
        end
      end

      resources :competences, :controller => 'curriculums/competences' do
        member do
          get 'graph'
          get 'courselist'
          get 'edit_prereqs'
        end
        
        resources :skills, :controller => 'curriculums/skills', :only => [:show]
        resources :courses, :controller => 'curriculums/courses', :only => [:show]
      end

      resources :courses, :controller => 'curriculums/courses' do  # ScopedCourses
        member do
          get 'edit_prereqs'
          get 'edit_as_a_prereq'
          get 'comments'
          post 'create_comment'
          get 'graph'
        end
      end

      resources :skills, :controller => 'curriculums/skills', :only => [:index, :create, :update, :destroy] do
        member do
          post 'add_prereq'
          post 'remove_prereq'
          put 'update_position'
        end
      end

      resources :roles, :controller => 'curriculums/roles', :only => [:new, :create, :destroy]
    end

    # My Plan
    resource :studyplan, :controller => 'plans', :only => [:show] do
      member do
        get :summary
      end
     
      resources :competences, :controller => 'plans/competences' do
        member do
          # get 'supporting'
          get 'delete'
        end
        
        resources :courses, :controller => 'plans/courses', :only => [:show, :create, :destroy] # show is obsolete
        resources :skills, :controller => 'plans/skills', :only => [:show]                      # obsolete
      end

      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]

      resource :schedule, :controller => 'plans/schedule', :only => [:show]

      resource :curriculum, :controller => 'plans/curriculums', :only => [:show, :edit, :update]
    end

    # Any plan (specify student ID)
    resources :plans, :constraints => { :id => /\w+/ }, :only => [:show, :update] do
      member do
        get :summary
      end
      
      get 'old_schedule', as: 'old_schedule'
      
      resources :courses, :controller => 'plans/courses',
        :only => [:index, :show, :create, :destroy]
#       resources :courses, :controller => 'plans/courses', :only => [:index, :show, :create]  # :except => [:edit, :update]
#       resource :schedule, :controller => 'plans/schedule', :only => [:show, :edit]
#       resource :record, :controller => 'plans/record', :only => [:show]
    end
    
    match 'search_courses' => "abstract_courses#search"
    resources :surveys, :only => [:show, :create], :constraints => { :id => /\w+/ }
  end

  resources :invitations, :only => [:show, :destroy], :id => /[^\/]+/

  #post 'client_side_error', :controller => 'application', as: 'client_side_error'
  match '/client_side_error' => 'application#client_side_error', as: 'client_side_error'
  match '/client_event', to: 'application#log_client_event', as: 'log_client_event'
  
  match '/:locale' => "frontpage#index", :as => :frontpage
  #root :to => "application#redirect_by_locale"
  root :to => "frontpage#index"

end

app/controllers/curriculums/competence_nodes_controller.rb
class Curriculums::CompetenceNodesController < CurriculumsController

  def nodes_by_skill_ids
    nodes_json = []
    
    if params[:ids]
      nodes = CompetenceNode.joins(:skills).where('skills.id' => params[:ids]).includes(:skills => [:skill_descriptions, :prereq_to]).uniq

      nodes_json = nodes.map do |node|
        if node.type == 'Competence'
          node.as_json(
            :only => [:id],
            :include => [
              {:skills => {
                  :only => [:id, :icon],
                  :include => {
                    :skill_descriptions => {
                      :only => [:id, :locale, :name]
                    },
                    :prereq_to => {:only => [:id, :requirement, :icon]}
                  }
              }},
              {:competence_descriptions => {
                  :only => [:id, :locale, :name, :description]
              }}
            ]
          )
        else 
          # Must be a ScopedCourse
          node.as_json(
            :only => [:id, :course_code],
            :include => [
              {:skills => {
                  :only => [:id, :icon],
                  :include => {
                    :skill_descriptions => {
                      :only => [:id, :locale, :name]
                    },
                    :prereq_to => {:only => [:id, :requirement, :icon]}
                  }
              }},
              {:course_descriptions => {
                  :only => [:id, :locale, :name]
              }}
            ]
          )
        end
      end
    end

    respond_to do |format|
      format.json { render :json => nodes_json, :root => false }
    end
  end


end

app/controllers/curriculums/competences_controller.rb
class Curriculums::CompetencesController < ApplicationController

  before_filter :load_competence, :only => [:edit, :edit_prereqs, :update, :graph, :courselist]
  
  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id] || params[:id])
  end
  
  def load_competence
    @competence = Competence.find(params[:competence_id] || params[:id])
    load_curriculum
  end

  def index
    load_curriculum
    @competences = Competence.where(:curriculum_id => @curriculum.id)
                    .joins(:competence_descriptions)
                    .where(["competence_descriptions.locale = ?", I18n.locale])

    respond_to do |format|
      format.json { render :json => @competences.select(<<-SQL
          competence_nodes.id,
          competence_descriptions.name AS translated_name
        SQL
      ).to_json(:methods => :strict_prereq_ids, :root => true) } # :skill_ids
    end
  end

  # curriculums/1/competences/1
  def show
    load_curriculum

    respond_to do |format|
      format.html {
        load_plan
    
        @competence = Competence.includes(:localized_description, {:skills => :localized_description}).find(params[:id])
        @chosen_competence_ids = @study_plan.competence_ids.to_set
        
        # Log
        @client_session_id = SecureRandom.hex(3)
        render :action => 'show', :layout => 'leftnav'
        log("view_competence #{@competence.id} (#{@client_session_id})")
      }

      format.json {
        @competence = Competence.includes(:skills => [:skill_descriptions, :skill_prereqs, :prereq_to]).find(params[:competence_id] || params[:id])
        render :json => @competence.to_json(
          :only => [:id],
          :include => {
              :skills => {
                :only => [:id, :icon],
                :include => {
                  :skill_descriptions => {
                    :only => [:id, :locale, :name]
                  },
                  :skill_prereqs => {:only => [:prereq_id, :requirement]}
                }
              },
              :competence_descriptions => {
                :only => [:id, :locale, :name]
              }
          },
          :root => true 
        )
      }
    end
  end

  # GET /competences/1/edit
  def edit
    authorize! :update, @competence

    # Add missing translations
    existing_locales = @competence.competence_descriptions.map {|description| description.locale}
    (REQUIRED_LOCALES - existing_locales).map do |locale|
      existing_locales = @competence.competence_descriptions << CompetenceDescription.new(:competence => @competence, :locale => locale, :name => '', :term_id => @curriculum.term_id)
    end

    render :action => 'edit', :layout => 'views/curriculums/container'
  end


  def edit_prereqs
    #@competence = Competence.find(params[:id])
    @competence_node = @competence
    authorize! :update, @competence

    @hide_help = cookies[:hide_edit_competence_prereqs_help] == 't' ? true : false

    @competence_node_url = curriculum_competence_path(:curriculum_id => @curriculum, :competence_id => @competence)

    render :action => 'edit_prereqs', :layout => 'views/curriculums/container'
  end

  # PUT /competences/1
  # PUT /competences/1.xml
  def update
    authorize! :update, @competence
    @curriculum.save  # Expire cache

    respond_to do |format|
      if @competence.update_attributes(params[:competence])
        format.html { redirect_to edit_curriculum_path(@curriculum) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def new
    load_curriculum
    @competence = Competence.new(:curriculum => @curriculum)

    authorize! :update, @curriculum

    REQUIRED_LOCALES.each do |locale|
      @competence.competence_descriptions << CompetenceDescription.new(:competence => @competence, :locale => locale, :term_id => @curriculum.term_id)
    end
    
    render :action => 'new', :layout => 'views/curriculums/browser'
  end

  def create
    load_curriculum
    authorize! :update, @curriculum
    @curriculum.save  # Expire cache
    
    @competence = Competence.new(params[:competence])
    @competence.term = @curriculum.term

    respond_to do |format|
      if @competence.save
        format.html { redirect_to(edit_curriculum_path(@curriculum), :notice => 'Competence was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def graph
    #@competence = Competence.find(params[:id])

    render :action => 'graph', :layout => 'views/curriculums/container'
  end
  
  def courselist
    #@competence = Competence.find(params[:id])
    
    render :action => 'courselist', :layout => 'views/curriculums/container'
  end
end

app/controllers/curriculums/roles_controller.rb
class Curriculums::RolesController < CurriculumsController
  before_filter :login_required
  before_filter :load_curriculum
  
  def load_curriculum
    @curriculum = Curriculum.find(params[:curriculum_id])
    authorize! :update, @curriculum
  end
  
  def new
    @invitations = TeacherInvitation.where(:target_id => @curriculum.id).all
    @subject = t("curriculums.roles.new.subject_default")
    @content = t("curriculums.roles.new.mail_template")
  end
  
  def create
    unless params[:addresses].blank?
      Curriculum.delay.invite_teachers(@curriculum.id, params[:addresses].split(/[,\s]/), params[:subject], params[:content])
    end
    
    #render :action => :new
    flash[:success] = t('curriculums.roles.new.sent_success')
    redirect_to curriculum_path(@curriculum)
  end
  
  def destroy
    user = User.find(params[:id])
    
    CurriculumRoles.where(:user_id => user.id, :target_id => @curriculum.id, :role => 'teacher').delete
    
    respond_to do |format|
      #format.html { redirect_to course_teachers_path(@course) }
      format.json { render :json => [user.id].as_json }
    end
  end
end
 

app/controllers/plans/courses_controller.rb
class Plans::CoursesController < PlansController

  #before_filter :login_required
  before_filter :load_plan

  # GET /studyplan/courses
  # GET /studyplan/courses.xml
  def index
    authorize! :read, @study_plan
    
    # Log
    @client_session_id = SecureRandom.hex(3)
    log("view_courses (#{@client_session_id})")
    
    respond_to do |format|
      format.html { render :action => 'index', :layout => 'affix-fixed' }
      format.xml  { render :xml => nil }
    end
  end

  # GET /studyplan/courses/1
  # GET /studyplan/courses/1.xml
  def show
    # Obsolete?
    authorize! :read, @study_plan
    @course = ScopedCourse.find(params[:id])
    @competence = nil
    @competence = Competence.find(params[:competence_id]) if params[:competence_id]

    # Log
    @client_session_id = SecureRandom.hex(3)
    if @competence
      log("view_competence_course #{@competence.id} #{@course.id} (#{@client_session_id})")
    else
      log("view_course #{@course.id} (#{@client_session_id})")
    end
    
    render :action => 'show', :layout => 'leftnav'
  end

  # Add course to study plan
  # POST /plans/:id/courses
  def create
    authorize! :update, @study_plan
    
    abstract_course = AbstractCourse.find(params[:abstract_course_id])
    competence_id = Integer(params[:competence_id]) rescue nil
    scoped_course_id = Integer(params[:scoped_course_id]) rescue nil
    
    scoped_course = nil
    
    
    plan_course = @study_plan.add_course(abstract_course, {
      competence_node_id: competence_id,
      scoped_course_id: scoped_course_id,
      manually_added: true
    })
    
    log "add_course #{abstract_course.id}, competence #{competence_id}, scoped_course #{scoped_course_id}"
    
    respond_to do |format|
      format.html {
        if competence_id
          competence = Competence.find(competence_id)
          redirect_to curriculum_competence_path(:curriculum_id => competence.curriculum_id, :id => competence_id), :flash => { :success => t('plans.courses.course_added_to_plan') }
          #studyplan_competence_path(:id => competence_id)
        else
          scoped_course = ScopedCourse.find(scoped_course_id) if scoped_course_id
          redirect_to root_path # FIXME
          # studyplan_competences_path, :flash => { :success => t('plans.courses.course_added_to_plan') }
        end
      }
      # TODO: add error message
      format.json { render json: { status: 'ok', plan_course_id: plan_course.id }.to_json( root: false ) }
    end
    
  end

  # Remove course from study plan. Use abstract_course_id
  # DESTROY /plans/:plan_id/courses/:id
  def destroy
    authorize! :update, @study_plan
    @competence = nil
    @competence = Competence.find(params[:competence_id]) if params[:competence_id]
    
    #if params[:abstract_course_id]
      status = @study_plan.remove_abstract_courses(params[:id])
      log "remove_course #{params[:id]}"
    #else
    #  status = @study_plan.remove_scoped_course(params[:id])
    #  log "remove_scoped_course #{params[:id]}"
    #end
    
    respond_to do |format|
      format.html {
        if @competence
          redirect_to curriculum_competence_path(curriculum_id: @competence.curriculum_id, id: @competence.id), :flash => { :success => t('plans.courses.course_removed_from_plan') }
        else
          redirect_to root_path # FIXME
          #studyplan_competences_path, :flash => { :success => t('plans.courses.course_removed_from_plan') }
        end
      }
      format.json { render json: { status: 'ok' }.to_json( root: false ) }
    end
  end

end

app/controllers/plans/curriculums_controller.rb
class Plans::CurriculumsController < PlansController

  before_filter :authenticate_user
  before_filter :load_plan, :only => :show

  # Make sure 'redirect_to' value is not saved here, because edit page uses it for redirect!
  skip_before_filter :store_location

  layout 'fixed'
  
  def show
    authorize! :read, @user
    
    # Store 'redirect_to' address so that cancel button works on edit page
    store_location
  end

  def edit
    @user = current_user
    authorize! :update, @user
    @curriculums = Curriculum.order(:start_year)
  end

  def update
    @user = current_user
    authorize! :update, @user
    
    if params[:user_study_plan]
      if @user.study_plan
        @user.study_plan.save
      else
        @user.create_study_plan()
      end
    end
    
    redirect_to studyplan_competences_path
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

  def skill_prereq(skill_id, prereq_id)
    p = SkillPrereq.find(:first, :conditions => {:skill_id => skill_id, :prereq_id => prereq_id})
    
    return '' unless p
    
    case p.requirement
    when STRICT_PREREQ
      return '<span style="font-size: 125%;">&diams;</span>'.html_safe
    when SUPPORTING_PREREQ
      return '<span style="font-size: 125%; color: gray;">&bull;</span>'.html_safe
    else
      return ''
    end
  end


  def scoped_course_comment(field)
    "<textarea name='comments[#{field}]' class='input-xxlarge' rows='5'>#{html_escape(@scoped_course.comment(field))}</textarea>".html_safe
  end
  
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/courses/_as_a_prereq_editor.html.erb
<div class="row-fluid full-height">

  <%= render 'current_course_column' %>

  <% content_for :searchable_column_heading do %>
    <%= t 'curriculums.courses.searchable_column.as_a_prereq_column_heading' %>
  <% end %>

  <%= render 'searchable_column' %>

</div>

<p><%= link_to t(:Back), edit_curriculum_path(@curriculum) %></p>

<%= render 'modals' %>

app/views/curriculums/courses/_form.html.erb
<%= form_for @abstract_course, :remote => true, :url => new_curriculum_course_path(params[:curriculum_id]) do |f| %>
  
  <div class="new-course-field-group">
    <%= f.label 'code', :class => 'new-course-label' %>
    <%= f.text_field :code, :class => 'new-course-field' %>
  </div>

  <%= f.fields_for :course_descriptions do |cf| %>
    <div class="new-course-field-group">
      <%= cf.label t("language_in_" + cf.object.locale), :class => "new-course-label" %>
      <%= cf.hidden_field :locale %>
      <%= cf.text_field :name, :class => "new-course-field" %>
    </div>
  <% end %>
<% end %>

app/views/curriculums/courses/comments.html.erb
<% content_for :title do %><%= @scoped_course.localized_name %><% end %>

<%= render 'tabs' %>

<div class="row">
  <div class="span12">
    <% @scoped_course.comments.each do |comment| %>
      <div class="comment">
        <p class="comment"><%= comment.comment %></p>
        <p class="sender">
          <% if comment.user %><%= comment.user.name %>,<% end %>
          <%=l comment.created_at %>
        </p>
      </div>
      <hr />
    <% end %>

    <p><%=t '.leave_new_comment' %></p>
    <%= form_for @new_comment, :url => create_comment_curriculum_course_path(:curriculum_id => @curriculum, :id => @scoped_course) do |f| %>
      <p><%= f.text_area :comment, :rows => 4, :class => 'input-xxlarge' %></p>

      <p><%= f.submit t(:Send), :class => 'btn btn-primary' %></p>
    <% end %>

  </div>
</div>

app/views/curriculums/courses/graph.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'views/curriculums/courseGraph' %>
<% end %>

<% content_for :title do %>
  <%= "#{@scoped_course.localized_name} - #{t('.title')}" %>
<% end %>


<%= render :partial => 'tabs' %>

<div id="course-graph" class="course-graph"
    data-graph-path="<%= graph_curriculum_path(:id => @curriculum.id) %>"
    data-source-id="<%= @scoped_course.id %>"
    >
    
    <!-- ko template: { name: 'courseTemplate', foreach: visibleCourses, afterRender: updateElementDimensions } --><!-- /ko -->
</div>

<%= render :partial => 'courses/graph_templates' %>

app/views/curriculums/courses/new.html.erb
<% content_for :title do %><%= @curriculum.name %> - <%=t '.create_course_heading' %><% end %>

<h1><%=t '.create_course_heading' %></h1>


<%= form_for @scoped_course, :url => curriculum_courses_path(@curriculum) do |f| %>
  <div class="form-control-group">
    <%= f.label t('.course_code'), :class => 'form-label' %>
    <div class="form-controls">
      <%= text_field_tag :course_code, @course_code, :class => 'field-lengthy' %>
      <span class="help-inline"><%=t '.create_course_hint' %></span>
    </div>
  </div>

  <div class="form-controls">
    <%= link_to t(:Cancel), edit_curriculum_path(@curriculum), :class => 'btn' %>
    <%= f.submit t(:Save), :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/curriculums/courses/show.html.erb
<!-- plans/courses/show -->
<% content_for(:javascripts) do -%>
  <%= javascript_tag do %>
    window.client_session_id = '<%= @client_session_id %>';
  <% end %>
  <%= javascript_include_tag 'views/plans/courses/show' %>
<% end -%>
<% content_for :title do -%>
  <%= @course.course_code %> <%= @course.localized_name %>
<% end -%>
<% content_for(:leftnav) do -%>
  <% if @competence %>
    <% if @competence.parent_competence %>
      <!-- This is a sub competence -->
      <h1><%= link_to @competence.parent_competence.localized_name, curriculum_competence_path(curriculum_id: @curriculum, id: @competence.parent_competence) %></h1>
      <h2><%= @competence.localized_name %></h2>
      <ul>
        <% @competence.supporting_prereq_courses.each do |course| %>
          <li class="<%= course == @course ? 'selected' : '' %>"><%= link_to course.localized_name, curriculum_competence_course_path(curriculum_id: @curriculum, competence_id: @competence.id, id: course) %>
        <% end %>
      </ul>
      
      <h2><%= t('.other_courses') %></h2>
      <ul>
        <% @competence.parent_competence.recursive_prereq_courses.each do |course|%>
          <li class="<%= course == @course ? 'selected' : '' %>"><%= link_to course.localized_name, curriculum_competence_course_path(curriculum_id: @curriculum, competence_id: @competence.parent_competence.id, id: course) %>
        <% end %>
      </ul>
    <% else %>
      <!-- This is a top-level competence -->
      <h1><%= link_to @competence.localized_name, curriculum_competence_path(curriculum_id: @curriculum, id: @competence) %></h1>
      <!--h2><%= t('.competence_courses') %></h2-->
      
      <ul>
        <% @competence.recursive_prereq_courses.each do |course| # TODO: move the query to controller
        %>
          <li class="<%= course == @course ? 'selected' : '' %>"><%= link_to course.localized_name, curriculum_competence_course_path(curriculum_id: @curriculum, competence_id: @competence.id, id: course) %>
        <% end %>
      </ul>
    <% end %>

  <% else %>
    <h1><%= link_to @curriculum.name, @curriculum %></h2>
    <ul>
      <% @study_plan.scoped_courses.each do |course| %>
        <li class="<%= @study_plan.passed?( course.abstract_course ) ? 'passed' : '' %> <%= course == @course ? 'selected' : '' %>"><%= link_to course.localized_name, curriculum_course_path(curriculum_id: @curriculum, id: course) %>
      <% end %>
    </ul>
  <% end %>

<% end -%>

<% if can? :update, @course %>
  <ul class="nav nav-pills pull-right">
    <li><%= link_to t('Admin_view'), edit_prereqs_curriculum_course_path(curriculum_id: @curriculum, id: @course) %></li>
    <li class="active"><%= link_to t('Student_view'), curriculum_course_path(curriculum_id: @curriculum, id: @course) %></li>
  </ul>
<% end %>

<h1>
  <%= @course.course_code %> <%= @course.localized_name %> (<%= @course.credits %> <%=t 'cr' %>)

  <!-- Add / Remove -->
  <% if can? :choose, ScopedCourse %>
    <% if @study_plan.has_abstract_course?(@course.abstract_course_id) %>
      <% if @competence %>
        <% top_competence = @competence.parent_competence || @competence %>
        
        <%= link_to studyplan_competence_course_path(:competence_id => top_competence.id, :id => @course.abstract_course_id), {:method => :delete, :class => 'btn btn-default'} do %>
          <i class="icon icon-minus"></i> <%= t('.course_remove_from_plan') %>
        <% end %>
      <% else %>
        <%= link_to studyplan_course_path(:id => @course.abstract_course_id), {:method => :delete, :class => 'btn btn-default'} do %>
          <i class="icon icon-minus"></i> <%= t('.course_remove_from_plan') %>
        <% end %>
      <% end %>
    <% else %>
      <% if @competence %>
        <% top_competence = @competence.parent_competence || @competence %>
        <%= link_to studyplan_competence_courses_path(:competence_id => top_competence.id, :scoped_course_id => @course.id, :abstract_course_id => @course.abstract_course_id), {:method => :post, :class => 'btn btn-default'} do %>
          <i class="icon icon-plus"></i> <%= t('.course_add_to_plan') %>
        <% end %>
      <% else %>
        <%= link_to studyplan_courses_path(:scoped_course_id => @course.id, :abstract_course_id => @course.abstract_course_id), {:method => :post, :class => 'btn btn-default'} do %>
          <i class="icon icon-plus"></i> <%= t('.course_add_to_plan') %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</h1>

<% if can?(:update, @curriculum) && @course.locked %>
  <!-- Editing disabled -->
  <div class="alert alert-info">
    <%=t '.locked' %>
  </div>
<% end %>

<!-- Course description -->
<% if @course.localized_description %>
  <% ld = @course.localized_description %>
  
  <% if !ld.default_period.blank? %>
    <p><strong><%=t ('.period') %></strong>: <%= ld.default_period %></p>
  <% elsif !ld.period_info.blank? %>
    <p><strong><%=t ('.period') %></strong>: <%= ld.period_info.html_safe %></p>
  <% end %>

  <% unless ld.content.blank? %>
    <p><%= ld.content.html_safe %></p>
  <% end %>
  
  <% # if @user.treatment != TREATMENT_GRAPH && @course.localized_description && !@course.localized_description.outcomes.blank?
  %>
  <% unless ld.outcomes.blank? %>
    <strong><%=t ('.learning_outcomes') %></strong>: <%= ld.outcomes.html_safe %>
  <% end %>
  
  <% unless ld.noppa_url.blank? && ld.oodi_url.blank? %>
    <p>
      <strong><%=t ('.links') %></strong>:
      <% unless ld.noppa_url.blank? %>
        <a target="_blank" href="<%= ld.noppa_url %>">Noppa</a>
      <% end %>
      
      <% unless ld.oodi_url.blank? %>
        <a target="_blank" href="<%= ld.oodi_url %>">Oodi</a>
      <% end %>
    </p>
  <% end %>

  <% unless ld.assignments.blank? %>
    <p><strong><%=t ('.assignments') %></strong>: <%= ld.assignments.html_safe %></p>
  <% end %>
  
  <% unless ld.replaces.blank? %>
    <p><strong><%=t ('.replaces') %></strong>: <%= ld.replaces.html_safe %></p>
  <% end %>
<% end %>


<% # if @user.treatment != TREATMENT_TRADITIONAL
%>
  <h2><%=t :Course_graph %></h2>
  <%= render :partial => 'courses/graph_templates' %>
  
  <% if @competence %>
    <div id="course-graph" class="course-graph"
      data-graph-path="<%= graph_curriculum_path(:id => @curriculum.id) %>" 
      data-source-id="<%= @course.id %>"
      data-target-id="<%= (@competence.parent_competence || @competence).id %>"
      >
      <!-- ko template: { name: 'courseTemplate', foreach: visibleCourses, afterRender: updateElementDimensions } --><!-- /ko -->
    </div>
  <% else %>
    <div id="course-graph" class="course-graph"
      data-graph-path="<%= graph_curriculum_path(:id => @curriculum.id) %>" 
      data-source-id="<%= @course.id %>"
      >
      <!-- ko template: { name: 'courseTemplate', foreach: visibleCourses, afterRender: updateElementDimensions } --><!-- /ko -->
    </div>
  <% end %>


<h2><%= t('.reqursive_prereqs') %></h2>

<% has_prereqs = false %>
<% if @course.localized_description && !@course.localized_description.prerequisites.blank?
# && @user.treatment != TREATMENT_GRAPH 
  has_prereqs = true
  -%>
  <%= @course.localized_description.prerequisites.html_safe %>
<% end %>

<% prereqs = @course.recursive_prereq_courses %>
<% unless prereqs.empty?
  has_prereqs = true
  %>
  <p>
    <ul>
      <% prereqs.each do |prereq_course| %>
        <% if @competence %>
          <li><%= link_to prereq_course.course_code + ' ' + prereq_course.localized_name, curriculum_competence_course_path(curriculum_id: @curriculum, competence_id: @competence.id, id: prereq_course) %></li>
        <% else %>
          <li><%= link_to prereq_course.course_code + ' ' + prereq_course.localized_name, curriculum_course_path(curriculum_id: @curriculum, id: prereq_course) %></li>
        <% end %>
      <% end %>
    </ul>
  </p>
<% end %>

<% unless has_prereqs %>
  <p><%=t :course_no_prereqs %></p>
<% end %>